### ISSUE TITLE
Error when activating add-on

### ISSUE THREAD

**Issue by Leon-Cantin** [ucupumar/yPanel#1]
![image](https://cloud.githubusercontent.com/assets/755263/25638330/0c43ed40-2f56-11e7-9630-86d6a6cf3d73.png)

I get this error when trying to activate the add-on from the add-ons menu. I installed it manualy by placing the file in my script folder since i don't like where Blender installs the add-ons when using the "Install from file"

cheers

**Comment by ucupumar** [comment]
It looks like the addon will still fails if you don't put it in AppData folder on Windows. I'll take a closer look into this issue.

**Comment by ucupumar** [comment]
I already fix this problem, now yPanel works with blender portable.
