### ISSUE TITLE
Displays options not saved and causing crashes

### ISSUE THREAD

**Issue by Lauloque** [ucupumar/yPanel#10]
On Blender 2.79.1 (bleeding edge) :
As shown in the video linked bellow, enabling and disabling parts of the addon is'nt correctly saved through Blender restarts. And for the top header it can even cause crashes. I couldn't reproduce it but once it happened that when closing blender after disabling both bars, I had the warning message for unsaved content (i did nothing but changing the addon options and save user settings) and after restarting Blender, only the bottom bar remained disabled. The top one was still here, like if the display options was not stored in the addon's preferences but instead, in the project state or something ?

I also tried to save the startup file, but it doesn't work around either.

[Video demo](https://youtu.be/zeSsGKZx890)

**Comment by ucupumar** [comment]
Maybe this issue related to #9, but please try if you can reproduce this bug using official blender 2.79.

**Comment by ucupumar** [comment]
I think this one is also fixed in the latest commit
