### ISSUE TITLE
matcap normal map regression?

### ISSUE THREAD

**Issue by spiraloid** [ucupumar/yPanel#11]
Thanks for fixing the 2.79 error on bake.  seems to work, but I'm not seeing the normal mapping on the matcap in solid mode.  am I missing something?

**Comment by ucupumar** [comment]
It works fine here. Can you give me an example blend file?

**Comment by spiraloid** [comment]
I'm a moron.  I didn't turn on the material override.

**Comment by ucupumar** [comment]
Lol, I'm closing this issue then.

**Comment by spiraloid** [comment]
please do. although if someone bakes in solid mode w a matcap it's reasonable to assume they might want it on.  but regardless great work.
