### ISSUE TITLE
Error when baking hidden object

### ISSUE THREAD

**Issue by gnuton** [ucupumar/yPanel#12]
Hi and thanks for the great tool.
I just found a small glitch. When you bake an object which is not visible you get a RuntimeError.

As you may see from the below screenshot Suzanne is hidden. I press bake and it trows the exception.
![image](https://user-images.githubusercontent.com/576580/37879729-e44b8410-3085-11e8-9cae-a297d4e2c209.png)

**Comment by ucupumar** [comment]
How can you bake hidden objects? Can you upload a video of how to produce the error?

**Comment by ucupumar** [comment]
Ok, nevermind, I already fixed it. Try to reinstall the addon again.

**Comment by gnuton** [comment]
Thanks. Exceptions say nothing. They are crashes which happen when programmers do not handle corner cases. Errors on the othe hand, tell people what's wrong with a nice and human readable message.
