### ISSUE TITLE
Installing 2.82

### ISSUE THREAD

**Issue by pixelinkmedia** [ucupumar/yPanel#14]
I installed add-on.

Doesn't display on Blender 2.82 interface that I can see

Where is it??

**Comment by Lauloque** [comment]
as far as i know, this addon hasn't been updated for the 2.8 series, so it might not be compatible at all.

**Comment by ucupumar** [comment]
Yes, this addon won't support Blender 2.8x because of it lacks of Blender Internal renderer. I'm still developing other addon with similar function for Blender 2.8x, hopefully I can share that in near future.

**Comment by pixelinkmedia** [comment]
Thanks for getting back to me.

**Comment by winniejo** [comment]
@ucupumar  To put it in Blender 2.8 would be brilliant !
Also if someone could make the CloneBrush more like Phototshop would also be a hugh improvement.

Winnie
stay save
