### ISSUE TITLE
Saving All Images - Invalid Path

### ISSUE THREAD

**Issue by enzyme69** [ucupumar/yPanel#2]
![screen shot 2017-05-03 at 11 33 52](https://cloud.githubusercontent.com/assets/3952687/25645723/7da2da66-2ff4-11e7-8dd7-5614c2f8ae61.png)

Wonder what's the default for Save All Images, I assume the tmp but not seeing it. Saving Image is ok though.

**Comment by ucupumar** [comment]
Save All won't save files automatically if you haven't pack or save them. I just use Blender own 'Save All'  operator (_bpy.ops.image.save_dirty_) for this, so that's kinda expected behavior I guess.
