### ISSUE TITLE
Materials panel will not show up for Curves

### ISSUE THREAD

**Issue by Leon-Cantin** [ucupumar/yPanel#4]
Hi it's me again,
I am a big fan of curves and i noticed that the material panel will not show up in the n-panel when i have a curve selected even though it has a material.

Thanks a lot for your hard work.

![image](https://cloud.githubusercontent.com/assets/755263/25665285/231fcc06-2feb-11e7-8549-3a4b3785733f.png)

**Comment by ucupumar** [comment]
Fixed!
