### ISSUE TITLE
panel options not showing

### ISSUE THREAD

**Issue by vaibhavraje** [ucupumar/yPanel#5]
hello this is very good addon in 1st look
loking forward to try it out its awsome futures but theres a problem
i cant find paint slot, bake tools, multires options anywhere.
i dont know what iam doing wrong or its an error.
attaching screenshot for help

![screen](https://cloud.githubusercontent.com/assets/28951200/26449566/8b63c970-4170-11e7-9325-5d01501aad17.png)

thnx

**Comment by vaibhavraje** [comment]
ok i got it.
to see the paint slot we need to assign material to the selected object.

**Comment by ucupumar** [comment]
Sorry for late reply. Yeah, you need to add material to access paint slots. I'm closing this issue.
