### ISSUE TITLE
Enabling the addon duplicates the Info header

### ISSUE THREAD

**Issue by Lauloque** [ucupumar/yPanel#9]
On Blender 2.79.1 (bleeding edge) :
As shown in the video linked bellow, enabling the addon duplicates the Info header. And enabling/disabling multiple times can repeat the duplication (I achieved to have 5x the Info header content).
And the only way I found to remove the duplications is to first disable the entire addon, save the user settings and completelly restart Blender.
[Video demo](https://youtu.be/zeSsGKZx890)

**Comment by ucupumar** [comment]
Does it works with standard blender installation? I haven't tried latest blender yet, maybe there was API changes or something.

**Comment by Lauloque** [comment]
I just tried with 2.79, same problem.

**Comment by ucupumar** [comment]
I see, are you getting error on the console?

**Comment by Lauloque** [comment]
Nothing appears in the console when enabling it.
I guess that will make it harder for you. I sympathize. :')

**Comment by ucupumar** [comment]
How about when disabling the addon? Do you get any error on the console?

**Comment by Lauloque** [comment]
I have that :
```
search for unknown operator 'VIEW3D_OT_yp_only_render_toggle', 'VIEW3D_OT_yp_only_render_toggle'
search for unknown operator 'VIEW3D_OT_yp_material_shade_toggle', 'VIEW3D_OT_yp_material_shade_toggle'
search for unknown operator 'SCENE_OT_yp_use_simplify_toggle', 'SCENE_OT_yp_use_simplify_toggle'
search for unknown operator 'PAINT_OT_yp_image_paint_toggle', 'PAINT_OT_yp_image_paint_toggle'
search for unknown operator 'VIEW3D_OT_yp_only_render_toggle', 'VIEW3D_OT_yp_only_render_toggle'
search for unknown operator 'VIEW3D_OT_yp_material_shade_toggle', 'VIEW3D_OT_yp_material_shade_toggle'
search for unknown operator 'SCENE_OT_yp_use_simplify_toggle', 'SCENE_OT_yp_use_simplify_toggle'
search for unknown operator 'PAINT_OT_yp_image_paint_toggle', 'PAINT_OT_yp_image_paint_toggle'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.79\scripts\modules\bpy_types.py", line 673, in draw_ls
    func(self, context)
RecursionError: maximum recursion depth exceeded
```

**Comment by ucupumar** [comment]
Did you already use the newest addon version?

**Comment by Lauloque** [comment]
I downloaded it and tested it just now :
The info header is still duplicated, nothing apearing in the console.
Disabling it gives the following in the console :
```
search for unknown operator 'VIEW3D_OT_yp_only_render_toggle', 'VIEW3D_OT_yp_only_render_toggle'
search for unknown operator 'VIEW3D_OT_yp_material_shade_toggle', 'VIEW3D_OT_yp_material_shade_toggle'
search for unknown operator 'SCENE_OT_yp_use_simplify_toggle', 'SCENE_OT_yp_use_simplify_toggle'
search for unknown operator 'PAINT_OT_yp_image_paint_toggle', 'PAINT_OT_yp_image_paint_toggle'
search for unknown operator 'VIEW3D_OT_yp_only_render_toggle', 'VIEW3D_OT_yp_only_render_toggle'
search for unknown operator 'VIEW3D_OT_yp_material_shade_toggle', 'VIEW3D_OT_yp_material_shade_toggle'
search for unknown operator 'SCENE_OT_yp_use_simplify_toggle', 'SCENE_OT_yp_use_simplify_toggle'
search for unknown operator 'PAINT_OT_yp_image_paint_toggle', 'PAINT_OT_yp_image_paint_toggle'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.79\scripts\modules\bpy_types.py", line 673, in draw_ls
    func(self, context)
RecursionError: maximum recursion depth exceeded
```
By the way, I may be wrong but I think the previous version was already "0, 1, 0" as it is today. If so, maybe you could update the version ID so that we can easily identify what update we are working with. And a slight changelog in the readme.md would be great to.
I know it's additional work for you but I'm sure it won't be useless.

**Comment by ucupumar** [comment]
Please delete old yPanel directory before installing the new one just to make sure everything's updated. I already test on other system, even on bleeding edge Blender to make sure I already eliminated this bug.

Unfortunately, version still doesn't mean anything, I just randomly put '0.1.0' when I first started developing this addon. Also, yPanel still kinda a mess in the documentation side. I want to organize more about this stuff but other projects prevent me to do it.
